# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "64bf2e7b47bb0196716d5fdcb77089c8"
name = "shop_manager_app"
application_url = "https://monkey-tight-lab.ngrok-free.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = ["fulfillment_orders/fulfillment_request_submitted"]
  uri = "https://n8n.avendano.site/webhook-test/fulfillment-request"

  [[webhooks.subscriptions]]
  topics = ["fulfillment_orders/cancellation_request_submitted"]
  uri = "https://n8n.avendano.site/webhook-test/cancellation-request"

  [[webhooks.subscriptions]]
  topics = ["fulfillments/create"]
  uri = "https://n8n.avendano.site/webhook-test/fulfillments-create"

  [[webhooks.subscriptions]]
  topics = ["fulfillments/update"]
  uri = "https://n8n.avendano.site/webhook-test/fulfillments-update"

[access_scopes]
scopes = "read_locations, write_products, read_assigned_fulfillment_orders,read_fulfillments,read_orders,write_fulfillments,write_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://monkey-tight-lab.ngrok-free.app/accounts/shops/callback/" ]


